org.gradle.jvmargs=-Xmx2G
modName=MoogsNetherStructures
minecraftVersion=1.20
modVersion=2.0.4
modId=mns
modDescription=loads of structures made with vanilla blocks and entities bringing life to your world! Discover loot, enemies, & more along the way!
modHomepage=https://www.curseforge.com/minecraft/mc-mods/mns-moogs-nether-structures
modSources=https://github.com/FinnSetchell/MoogsNetherStructures2
modReleases=https://github.com/FinnSetchell/MoogsNetherStructures2/releases
modIssues=https://github.com/FinnSetchell/MoogsNetherStructures2/issues
modDiscord=https://discord.gg/S5nffJbuvA
modKofi=https://ko-fi.com/finndog
modCurseforge=https://www.curseforge.com/minecraft/mc-mods/mns-moogs-nether-structures
modModrinth=https://modrinth.com/mod/mns-moogs-nether-structures

structureLibVersionRange=[1.0.0,)

publishDisplayPrefix=MNS
publishDisplaySuffix=[UNIVERSAL]

modrinthProjectId=nGUXvjTa
curseforgeProjectId=967466
curseforgeProjectSlug=mns-moogs-nether-structures
publishMcStart=1.20
publishMcEnd=1.20.6

discordAvatarUrl=https://media.forgecdn.net/avatars/thumbnails/939/604/64/64/638419616560253774.png
discordEmbedColor=#c20045
discordThumbnailUrl=https://media.forgecdn.net/avatars/thumbnails/939/604/64/64/638419616560253774.png
discordBannerUrl=https://www.bisecthosting.com/images/CF/Moogs_Nether_Structures/BH_MNS_header.webp
discordRoleId=1466012771379581039
discordPing=false
