org.gradle.jvmargs=-Xmx2G
modName=MoogsNetherStructures
minecraftVersion=1.21
modVersion=2.0.3
modId=mns

# Mod metadata
modDescription=Many structures made with vanilla blocks and entities bringing life to your world! Discover loot, enemies, & villagers along the way!
modHomepage=https://www.curseforge.com/minecraft/mc-mods/mns-moogs-nether-structures
modSources=https://github.com/FinnSetchell/MoogsNetherStructures2
modIssues=https://github.com/FinnSetchell/MoogsNetherStructures2/issues
structureLibVersionRange=[1.0,)

# Publishing display customization
publishDisplayPrefix=MNS
publishDisplaySuffix=[UNIVERSAL]

# Publishing platform settings
modrinthProjectId=nGUXvjTa
curseforgeProjectId=967466
curseforgeProjectSlug=mns-moogs-nether-structures
publishMcStart=1.21
publishMcEnd=1.21.10
discordEmbedColor=#c20045